name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black

    - name: Format with Black
      run: black --check interface/st_interface.py

    - name: Lint with flake8
      run: flake8 interface/st_interface.py --ignore=E402,E501 --max-line-length=100
      
    - name: Test Streamlit app
      run: |
        streamlit run interface/st_interface.py --help

    - name: Install Hadolint
      run: |
        sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
        sudo chmod +x /bin/hadolint

    - name: Lint Dockerfile
      run: hadolint Dockerfile

    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_IMAGE }} .

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ${{ env.DOCKER_IMAGE }}